### ISSUE TITLE
00 chat lines ending with \ cause issue on log import

### ISSUE THREAD

**Issue by valarnin** [ravahn/FFXIV_ACT_Plugin#250] opened 2020-04-22 22:29 UTC
When importing a network log, if a 00 chat line ends with a `\` the next line gets appended to the previous line on import.

Consider the following network log lines:

```
00|2020-04-16T17:49:40.0000000-04:00|000f|Some Person|                \|51bf3d4f7ffb3365ae16de48f86c7fa9
38|2020-04-16T17:49:40.8090000-04:00|12345678|Some Otherperson|32503218|6140|6140|9040|10000|224|0|-109.3564|174.2756|650.8196|-1.548274|0|70|0||7031f320c8dd011c6a26d1d5f36b60c7
```

This results in the following line being emitted on import:

```
[17:49:40.000] 00:000f:Some Person:[17:49:40.809] 26:12345678:Some Otherperson:32503218:6140:6140:9040:10000:224:0:-109.3564:174.2756:650.8196:-1.548274:0:70:0:
```

I can provide the full log file if needed, but it's 100+ MB and I'd rather not upload it publicly.

**Comment by ravahn** [comment] 2020-07-19 23:01
closing for now since neither of us could reproduce this.   I traced through the code to figure out how it would be possible for one ACT line to blend into the next, and I couldnt see how, so will need something that reproduces it.

**Closed by ravahn** 2020-07-19 23:01 UTC
