### ISSUE TITLE
Turrets deaths count as deaths for a Machinist

### ISSUE THREAD

**Issue by UDK450** [ravahn/FFXIV_ACT_Plugin#151] opened 2018-03-13 18:31 UTC

**Comment by ravahn** [comment] 2018-03-18 00:15
I previously added a work-around for this but it hard-coded the english name for the turrets.  I have modified it to hopefully work for all four languages supported by the plugin.  this will go out in the next release.  If it still doesn't work, then I'll have to dig deeper into the cause.

**Comment by wingchaos** [comment] 2018-04-25 15:40
it's that ok ?like this
if PET death.
PET's owner death count -1.
of course you can do it in overlaySkin

**Comment by ravahn** [comment] 2019-01-27 01:36
I recently discovered that the previous work-around did not actually work most of the time.  This will be fixed in the next release, soon.

**Closed by ravahn** 2019-01-27 01:36 UTC
Labels: bug
