### ISSUE TITLE
FFXIV ACT Parser

### ISSUE THREAD

**Issue by RoboWabbzy** [ravahn/FFXIV_ACT_Plugin#258] opened 2020-12-16 20:35 UTC
I was setting up a parser for my gf so she can use it for ff14 raids and we keep running into a "No Network Data Detected" error when testing the game connection. We've added an exception to the firewall, turned it off, running ACT in admin, also added it to inbound and outbound in the firewall. There also isn't any vpn, third party firewall, or anti-lag software. I'm not sure what else to do to fix this issue. Any suggestions? 
![Capture](https://user-images.githubusercontent.com/76129737/102403393-332a3780-3fb4-11eb-9306-cf5c38aec99a.PNG)

**Comment by werewolfboy13** [comment] 2020-12-16 22:01
This would be better to ask in the discord.

**Comment by ravahn** [comment] 2020-12-23 03:38
If you haven't resolved this, the discord community is very helpful for resolving issues like this.    You can join the discord via this invite: https://discord.gg/ahFKcmx

One possibility for the cause is anti-virus software besides windows defender, or vpn software.  Often installing winpcap and configuring the plugin to use it solves the issue for difficult cases.  Closing this issue.

**Closed by ravahn** 2020-12-23 03:38 UTC
