### ISSUE TITLE
1.5.1.4 issues with DirectHitPct, DirectHitCount, CritDirectHitCount, CritDirectHitPct

### ISSUE THREAD

**Issue by christianallred** [ravahn/FFXIV_ACT_Plugin#90] opened 2017-06-28 04:52 UTC
My log
`Hits` 113

Ones of these two numbers below is wrong. i am going to assume its the count. as that seems REALLY high for 113 hits. 
`DirectHitCount` 54  
`DirectHitPct` 8.0%

It would appear that the percent is being calculated wrong, or the count is wrong. 
6 / 113 = 5.3%
`CritDirectHitCount` 6
`CritDirectHitPct` 0.9%

**Comment by christianallred** [comment] 2017-06-28 04:56
Also CritDirectHitPct seems to have disappeared

**Comment by wingchaos** [comment] 2017-06-28 08:12
1.5.1.4  Healer 's  DirectHitCount &DirectHitPct&CritDirectHitCount&CritDirectHitPct    do not  work  normally...All them   display "0" .

**Comment by Squall-Leonhart** [comment] 2017-06-28 08:32
doesn't autoattack also trigger directhits?

**Comment by hibiyasleep** [comment] 2017-06-28 09:51
Here's more issue: `DirectHitCount` is 18, so well `DirectHitPct` is 20%, but `swings` is 15.

**Comment by christianallred** [comment] 2017-06-28 19:49
@Squall-Leonhart I have not seen it happen but i ahven't been looking for it either. I will test that out tonight.

**Comment by christianallred** [comment] 2017-06-28 19:50
@wingchaos Are you sure you are on 1.5.1.4? they all show up just fine for me in ACT. they just appear to be calculated wrong. I am getting no 0 values. 

Are you looking in ACT? or in your overlay?

**Comment by Squall-Leonhart** [comment] 2017-06-28 23:36
I did one run of Praetorium as healer

DirectHits % were recorded

I did runs of Doma, Castrum Abania as healer

No directhits % were recorded

**Comment by GB19xx** [comment] 2017-06-29 00:36
山田太郎 が「いいね！」を返しました。
Spark by Readdle

**Comment by Firesped** [comment] 2017-06-29 08:39
I was doing auto attack skill speed tests on my monk. Auto Attack procs for both DH and Criticals. I'm am transfering the data into a spread sheet for calculations of what I want. 

I noticed the Encounter View is showing different information then Combatant View. 
Encounter View: hits: 355 CritHits: 44 DirectHitCount: 402 CritDirectHitCount: 42
Combatant View: hits: 355 CritHits: 44 DirectHitCount: 134 CritDirectHitCount: 14

I have questions about the data here. does hits include all times? does crit include CDH? does DH include CDH?

**Comment by ravahn** [comment] 2017-06-29 13:54
Heals do not direct hit based on my own and other's analysis, so I'm going to disregard any reports of DH heals being 0% since they are per SE's game design.  The added combatantdata export variables used by overlays, as well as the new ACT columns, only report damage data.

I just re-tested the act columns and found:
CombatantData: DirectHitPct, CritDirectHitPct, CritDirectHitCount are correct, but DirectHitCount is wrong.
DamageTypeData: DirectHitPct, CritDirectHitPct, CritDirectHitCount, and DirectHitCount are correct
AttackType: DirectHitPct, CritDirectHitPct, CritDirectHitCount, and DirectHitCount are correct

DirectHitCount is incorrect on the combatant level because it is summing up all of the DirectHitCounts from the DamageType level, which is redundant - it includes All and other groupings.  This will be fixed in the next release.

Next I will re-test the combatant level ExportVariables used by overlays.

**Comment by ravahn** [comment] 2017-06-29 14:51
This should now be fixed for the next version.  The export variables for CritDirectHitPct was raising an exception, which would significantly degrade performance as well as not function, due to a type conversion error.

**Comment by christianallred** [comment] 2017-06-29 19:00
Thanks Ravahn, 

I guess i should have specified in my post. but i was not looking at heals in any ways. I was looking at dmg in all of my findings.

**Comment by cschmidt0121** [comment] 2017-06-29 19:03
https://www.reddit.com/r/ffxiv/comments/6jo4u0/direct_hit_fey_union_efficacy/

Have you seen this? Not sure if it just muddies the waters but it seems direct hit is doing _something_ for healers.

**Comment by ravahn** [comment] 2017-06-30 13:55
This is fixed in release v1.5.1.5.

Regarding fey union - if the game is not sending heal direct hit data, and the heal amounts do not show damage differences apart from critical hits, then everything's working as designed by SE.

If SE starts sending DH data for heals the same way it does for Attacks, which seems likely, then the plugin will pick it up and will not need any updates.

**Closed by ravahn** 2017-06-30 13:55 UTC
Labels: bug
