### ISSUE TITLE
ACT/FFXIV Plugin is crashing game, cannot connect to data center when ACT is open

### ISSUE THREAD

**Issue by Kunalm77** [ravahn/FFXIV_ACT_Plugin#248] opened 2020-04-08 05:58 UTC
Hi,

I am not able to connect to the data center while ACT is launched. When I test the game connection it says it detects the game but the plugin might need to be updated if the game was updated. There was a patch last night. I am aware of the latest release version being compatible with the new patch but I'm still getting this issue. Please let me know if you have a solution, thanks!

**Comment by valarnin** [comment] 2020-04-08 07:53
Please provide more information:

- Language of your game client
- Language you have the FFXIV ACT plugin set to
- A full list of plugins you're loading in ACT, their versions, and the order they're being loaded in
- Whether the game still crashes if you start ACT after already being logged in to a character

**Comment by Kunalm77** [comment] 2020-04-08 18:43
- Game client language: English, Japanese audio
- Language for ACT plugin: English
- In Order: FFXIV_ACT plugin -> OverlayPlugin.dll
- I run the first and then load ACT, I see some of the ACT UI elements show up in the game UI but once I click Test Game Connection I get the message I mentioned previously and the game will crash after saying the connection to the server was lost.

**Comment by Kunalm77** [comment] 2020-04-08 18:45
- Tried loading only FFXIV_ACT_Plugin, Version=2.0.5.10, Culture=neutral, PublicKeyToken=null 
 - Crash is still occurring

**Comment by valarnin** [comment] 2020-04-08 19:39
This sounds like maybe firewall rule issues? Try completely removing the firewall rules and re-adding them. If that doesn't help then someone more knowledgeable will need to help sort you out, you might get faster help asking on the Discord in the `#troubleshooting` channel.

**Comment by EQAditu** [comment] 2020-04-08 20:47
Things like this are mysterious and rare.  The FFXIV Plugin doesn't do anything that should crash the game as it is only reading things and most of what it's reading is actually network rather than process memory.  If you're running 2.0.5.10 of the plugin and the plugin states that it might need to be updated due to a game update... then things are very wrong.  Your game client doesn't have the same memory pointers that other game clients have.  If true, that's reason enough to crash by itself... but it sounds like an improbable scenario.

**Comment by Kunalm77** [comment] 2020-04-09 00:55
@EQAditu What do you suggest I do? Should I reinstall the game?

**Comment by Kunalm77** [comment] 2020-04-09 01:10
Okay so I did the suggestion above and re-did my firewall exceptions for my anitvirus as well as windows firewall and now it seems to be working. I appreciate the swift replies!

**Comment by valarnin** [comment] 2020-04-09 16:37
If the problem is fixed please close the issue. Glad that the firewall changes worked for you. :smiley:

**Comment by Yomiko1978** [comment] 2020-04-29 20:00
I am having the same issue but re-adding the firewall didn't fix it.  I am on the English client with the English version of the plugin.  The game won't connect or will disconnect me if the parser is set to Network mode but the game works fine if the parser is set to memory.  Can anyone help?

**Comment by werewolfboy13** [comment] 2020-04-30 00:50
> I am having the same issue but re-adding the firewall didn't fix it. I am on the English client with the English version of the plugin. The game won't connect or will disconnect me if the parser is set to Network mode but the game works fine if the parser is set to memory. Can anyone help?

You'll have better luck asking in the discord. Can someone close out the ticket?

**Closed** 2020-07-19 15:39 UTC
