### ISSUE TITLE
O4s reporting incorrect skill names.

### ISSUE THREAD

**Issue by Pirate144** [ravahn/FFXIV_ACT_Plugin#203] opened 2019-01-30 06:08 UTC
Static did weekly O9s-O12s clears, decided to go back into O4s for fun because a few people hadn't done it before. We get to Neoexdeath and we notice our overlays reporting strange things, such as peoples max hits being "Big Hug", or a long strand of Japanese characters, or various crafting/gathering skill names.

And it was like that for everyone that was parsing but everyone had different results and names.

Example here of all incoming damage to neoexdeath. https://a.uguu.se/3lWewY7XRA5z_Advanced_Combat_Tracker_2019-01-29_22-59-09.png

Raw log file here: https://dl.dropboxusercontent.com/s/izvi0jc0yurcivh/Network_20190129.zip

As you can see in the log files it worked fine for O9s-O12s, but got broken during O4s.

Edit: Line 173575 is where we zone in O4s, 173851 is the first line where stuff gets weird, prepull Fey Wind is being read as "Eyes on Me", and everything after that just gets weirder.

**Comment by ravahn** [comment] 2019-02-02 19:12
This is very strange  Even though the skill IDs are wrong, the rest of the combat data looks correct - it shows damage type from thunder ii as piercing for a bard.  I suspect there is something unexpected happening in the network packet data that I used to write out combat events, but just in the area where the skill ID is recorded.  Maybe the field I am using is incorrect under certain circumsrtances, or it is being offset instead of fixed-position.  The game correctly interprets the data, so it is definitely a problem with my plugin,

Unfortunately, even though you provided an excellent log, I need to try to reproduce this with the "dump all network data" option turned on, so i can look at the other data in the network packet.  if you happen to experience it again, can you turn on this option for 30 or 60 sec, and then send me that log? it may get big if you leave it turned on for long.

**Comment by Pirate144** [comment] 2019-02-02 19:52
Sure, I'll give it a try next time I go in.

**Comment by Pirate144** [comment] 2019-02-14 06:51
https://dl.dropboxusercontent.com/s/jc3w2yrrq4bo7p2/Network_20190213.zip

Sorry about the wait, there ya go. We mashed as many buttons as possible. Yes there were 2 whit mages and 2 black mages.

Once again everyone ACT was recording different skill names.

**Comment by ravahn** [comment] 2019-03-02 16:45
Thanks, this helped a lot.  I'm updating the plugin to pull the skill ID from the DWORD 15 of the network packet instead of DWORD 10.  Will be fixed in the next plugin release.

**Comment by ravahn** [comment] 2019-07-13 01:22
Correction to my optimism from March 2 - the fix I tried didnt pass testing when shared with a larger group of people.  So, it was reverted.  This appears to be zone-specific to O4S.  I will take another stab at trying to find a solution.

**Comment by ravahn** [comment] 2019-07-30 18:32
The new patch 5.05 zones had a similar problem as O4S.  I released the previous fix in v2.0.2.9 of the plugin, since testing this morning with various people showed it was working both in savage and regular zones after some of the other changes I made.  Hopefully it will resolve this problem fully with no side effects, but won't know for a few days.

**Closed** 2019-08-17 20:14 UTC
Labels: bug
