### ISSUE TITLE
Add option to add extra DPS due to raid buffs to the person providing the buff

### ISSUE THREAD

**Issue by haasn** [ravahn/FFXIV_ACT_Plugin#222] opened 2019-07-01 14:57 UTC
Plenty of jobs provide raid buffs that increase damage dealt by others (I doubt I need to give examples).

Would it be possible to have an option that adds this DPS to the person providing the buff, instead of the people benefiting from it? For example, if under the effect of Trick Attack, my Fire IV hits for 10,000 damage - then treat it as 9090 damage for myself and add 910 to the NIN instead.

I'm especially interested in seeing how this affects the DPS of e.g. healers (in particular, AST) and stuff like dancer which does a lot of buffing. It would also paint a much more realistic picture of how much individual jobs/players are *actually* contributing to the raid DPS.

**Comment by ravahn** [comment] 2019-07-01 22:48
I understand the reasoning behind this request, but i'm not sure it's always clear what effect buffs really have, at least to the degree that is necessary to produce reproducable numbers.  tracking and calculating one trick attack buff is easy, but what if there are two NINs in an 8-man party, both with trick attack on the boss.  Which one gets the 10%?  Server-side I've seen evidence that it switches around based on whoever landed it most recently.  In practice, it would just produce an inaccurate parse. 

What about Battle Litany, Drg's +Crit buff?  The crit damage formula is approximated in ACT because it varies with skill/spell speed, so at best this would be a guess.  However, some jobs have guaranteed crit abilities, which would need to be accounted for.

Overall, some sort of estimate could probably be produced, but I think it is better left to the theorycrafters.  ACT will report real damage numbers as close as possible, and try to fill in the gaps for DoTs/HoTs (and hopefully damage shields), but I don't want to add a setting to reallocate real damage amounts from skills.

**Closed by ravahn** 2019-07-01 22:48 UTC
